#!/usr/bin/env python3
"""ableton_template.py - scaffold generator for an Ableton techno project."""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path


@dataclass
class ScaffoldReport:
    output_dir: str
    project_name: str
    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


def _write(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def build_scaffold(output_dir: str, project_name: str, force: bool = False) -> ScaffoldReport:
    out = Path(output_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    report = ScaffoldReport(output_dir=str(out), project_name=project_name)
    project_dir = out / project_name

    created_paths = [
        project_dir,
        project_dir / "Samples",
        project_dir / "Exports",
        project_dir / "Notes",
    ]
    for path in created_paths:
        path.mkdir(parents=True, exist_ok=True)
        report.created.append(str(path))

    files = {
        project_dir / "README.md": (
            f"# {project_name}\n\n"
            "Ableton techno scaffold generated by BAGO.\n"
            "Use this as a starting point for arrangement, drums, bass, and return tracks.\n"
        ),
        project_dir / "template.json": json.dumps(
            {
                "project_name": project_name,
                "type": "ableton-techno-4x4",
                "tempo_bpm": 130,
                "time_signature": "4/4",
                "tracks": [
                    "drums",
                    "bass",
                    "lead",
                    "pads",
                    "fx",
                ],
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
    }

    for path, content in files.items():
        if _write(path, content, force):
            report.created.append(str(path))
        else:
            report.skipped.append(str(path))

    return report


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate an Ableton techno project scaffold.")
    parser.add_argument("--output", default="build/ableton-template", help="Output directory for the scaffold")
    parser.add_argument("--name", default="AbletonTechnoProject", help="Project folder name")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    parser.add_argument("--json", action="store_true", help="Print JSON report")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        report = build_scaffold(args.output, args.name, force=args.force)
        payload = json.dumps(asdict(report), indent=2, ensure_ascii=False) + "\n"
        if args.json:
            print(payload, end="")
        else:
            print(f"Ableton scaffold created at: {report.output_dir}")
            print(f"Project: {report.project_name}")
            print(f"Created: {len(report.created)}")
            print(f"Skipped: {len(report.skipped)}")
        return 0
    except Exception as exc:
        print(f"ableton_template failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
